spring.application.name=backend
spring.datasource.url=jdbc:tc:postgresql:15-alpine:///justorder
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=esta-es-una-clave-super-secreta-y-muy-larga-para-jwt-123456789