spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/justorderdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=esta-es-una-clave-super-secreta-y-muy-larga-para-jwt-123456789